# -*- coding: utf-8 -*-
"""nightmap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zAlg9PubCEGixNHZKeLbZ0WqDLf4xZJ
"""

!pip install earthengine-api --upgrade
!pip install folium --upgrade

import ee
import folium

ee.Authenticate()

ee.Initialize()

#Loading the Night time Collection
collection = ee.ImageCollection('NOAA/DMSP-OLS/NIGHTTIME_LIGHTS')
# Extract the first image
first_image = collection.first()

# Display band information about the image
first_image.bandNames().getInfo()

collection = collection.select('stable_lights')


first_image = collection.first()
 
# Get number of years after 1991 from the first image
year = ee.Date(first_image.get('system:time_start')).get('year').subtract(1991)
 
# Turn it into a band
img1 = ee.Image(year).byte().addBands(first_image)
 
# A new band appears in the new image
img1.bandNames().getInfo()

def createTimeBand(img):
    year = ee.Date(img.get('system:time_start')).get('year').subtract(1991)
    return ee.Image(year).byte().addBands(img)
 
# Map it to the collection to create a new collection
collection = collection.map(createTimeBand)

# Define a method for displaying Earth Engine image tiles to folium map.
def add_ee_layer(self, ee_image_object, vis_params, name):
  map_id_dict = ee.Image(ee_image_object).getMapId(vis_params)
  folium.raster_layers.TileLayer(
    tiles = map_id_dict['tile_fetcher'].url_format,
    attr = 'Map Data © <a href="https://earthengine.google.com/">Google Earth Engine</a>',
    name = name,
    overlay = True,
    control = True
  ).add_to(self)
 
# Add EE drawing method to folium.
folium.Map.add_ee_layer = add_ee_layer

# Create the night map
night_map = folium.Map(location=[37.5010, -102.1899], zoom_start=4.5)

#  visualize the y-intercept in green, and positive/negative slopes as red/blue.
params = {
    'bands' :  ['scale', 'offset', 'scale'],
    'min' : 0,
    'max' : [0.18, 20, -0.18],
}

night_light = collection.reduce(ee.Reducer.linearFit())

# Add the image layer to the night_map
night_map.add_ee_layer(night_light, params, 'test')
 
# Display the map
display(night_map)